### ISSUE TITLE
bug: statsmodels 0.14.5 fails to build on linux on Python 3.11 when using gcc 11 (RedHat UBI 9)

### ISSUE THREAD

**Issue by AlessandroPomponio** [statsmodels/statsmodels#9593]
#### Describe the bug

`statsmodels` fails to build on Linux on Python 3.11 when using Red Hat UBI 9, breaking installation of Scipy. This seems to be due to GCC 11.

#### Code Sample, a copy-pastable example if possible

```
docker run --rm --entrypoint bash mirror.gcr.io/redhat/ubi9:latest -c "yum update -yq && yum install -yq python3.11 python3.11-pip gcc && pip3.11 install statsmodels"
```

Full output log: 

[statsmodel-failure.txt](https://github.com/user-attachments/files/21103672/statsmodel-failure.txt)

#### Expected Output

Successful installation of statsmodels

**Comment by AlessandroPomponio** [comment]
I see the error produced by the docker run command is not what I was after - I will update the issue in a bit

**Comment by pstrzelczak** [comment]
Related to https://github.com/statsmodels/statsmodels/issues/9592

**Comment by AlessandroPomponio** [comment]
> Related to [#9592](https://github.com/statsmodels/statsmodels/issues/9592)

Partially - building from source seems to fail on gcc 11 - `gcc (Debian 12.2.0-14+deb12u1) 12.2.0` seems to work when doing

```
docker run --entrypoint bash --rm ghcr.io/astral-sh/uv:python3.11-bookworm -c "uv pip install --system statsmodels"
```

**Comment by bashtage** [comment]
```
      statsmodels/tsa/stl/_stl.c:43:10: fatal error: Python.h: No such file or directory
         43 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
```

This is a local configuration error.  For some reason, the python you are using either does not have the development headers installed or you may need to set some custom includes. I don't think there is anything we can do. 

You can just use the wheels which are now fully available.
