### ISSUE TITLE
build on osx -python-3.4

### ISSUE THREAD

**Issue by epifanio** [statsmodels/statsmodels#1513]
Trying to build statmodels on a mac osx 10.9 running python 3.4 i got error.

i tried with both numpy from pip as well as a recente git version, same log : 

```
In file included from statsmodels/tsa/kalmanf/kalman_loglike.c:257:
In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1803:
/usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API
      NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
statsmodels/tsa/kalmanf/kalman_loglike.c:7021:19: error: no member named 'f_tstate' in 'struct _frame'
        (*frame)->f_tstate = PyThreadState_GET();
        ~~~~~~~~  ^
1 warning and 1 error generated.
error: command 'clang' failed with exit status 1
MacBook-Pro-di-Massimo-2:statsmodels epi$ 
```
