### ISSUE TITLE
cannot import name 'PytestTester'

### ISSUE THREAD

**Issue by jradis** [statsmodels/statsmodels#5182]
>      16 from statsmodels.tsa.arima_model import ARIMA as _ARIMA
>      17 from statsmodels.tsa.base.tsa_model import TimeSeriesModelResults
> ---> 18 from statsmodels import api as sm
>      19 
>      20 import numpy as np
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/api.py in <module>()
> ----> 1 from . import iolib
>       2 from . import datasets
>       3 from . import tools
>       4 from .tools.tools import add_constant, categorical
>       5 from . import regression
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/iolib/__init__.py in <module>()
>       3 from .smpickle import save_pickle, load_pickle
>       4 
> ----> 5 from statsmodels import PytestTester
>       6 test = PytestTester()
>       7 
> 
> ImportError: cannot import name 'PytestTester'

Upon further debugging , I got the response "Unable to determine path"

**Comment by jradis** [comment]
It was actually a problem with my ipykernel. Resolved by updating ipykernel

**Comment by kiumars1370** [comment]
hi, this error is not resolved.

**Comment by MVXHAOIUTW** [comment]
I updated my jupyter notebook and this error disappeared.

**Comment by poojajps13** [comment]
I am facing the same error .I am using spyder, how to resolve the issue?

**Comment by josef-pkt** [comment]
I reopen the issue.

Based on the previous comment that updating ipython resolved the issue, I guess this is a problem when the interpreter/notebook/spyder manipulates the path.
I never had a problem in spyder or jupyter notebooks, but I'm using old versions of both.

We try protect the call for availability of pytest, but the `__init__` raises if it cannot identify the package path.
Given that the tester is optional and not needed for running statsmodels, I think we can convert the ValueError to a Warning.
Even if there is a bug in the python environment/setup, we should still be able to use statsmodels.
Unless, of course, we need the underlying feature also in non-testing code.

```
class PytestTester(object):
    def __init__(self):
        f = sys._getframe(1)
        package_path = f.f_locals.get('__file__', None)
        if package_path is None:
            raise ValueError('Unable to determine path')
        self.package_path = os.path.dirname(package_path)
        self.package_name = f.f_locals.get('__name__', None)
```

possibly related: 
Based on what I looked at a long time ago (at the early stages of statsmodels), we cannot run statsmodels from a zipped source because we need the file names and access for the unit tests. (zip-safe=False). 
I don't know if it would work if unit test modules are excluded.

**Comment by michaellis93** [comment]
Hello I'm having a similar issue. Was the main fix to update you jupyter notebook?
How can I update my ju[yter notebook if I just updated anaconda?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-f6341ec44a25> in <module>
      2 import matplotlib as plt
      3 from scipy.stats import ttest_ind
----> 4 import statsmodels.api as sm

/anaconda3/lib/python3.6/site-packages/statsmodels/api.py in <module>
      5 from . import regression
      6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
----> 7 from .regression.recursive_ls import RecursiveLS
      8 from .regression.quantile_regression import QuantReg
      9 from .regression.mixed_linear_model import MixedLM

/anaconda3/lib/python3.6/site-packages/statsmodels/regression/recursive_ls.py in <module>
     14 from statsmodels.regression.linear_model import OLS
     15 from statsmodels.tools.data import _is_using_pandas
---> 16 from statsmodels.tsa.statespace.mlemodel import (
     17     MLEModel, MLEResults, MLEResultsWrapper)
     18 from statsmodels.tools.tools import Bunch

/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py in <module>
     27 from statsmodels.tools.tools import pinv_extended, Bunch
     28 from statsmodels.tools.sm_exceptions import PrecisionWarning
---> 29 import statsmodels.genmod._prediction as pred
     30 from statsmodels.genmod.families.links import identity
     31 import warnings

/anaconda3/lib/python3.6/site-packages/statsmodels/genmod/__init__.py in <module>
----> 1 from statsmodels import PytestTester
      2 test = PytestTester()
      3 

ImportError: cannot import name 'PytestTester'

**Comment by larissalong** [comment]
> Hello I'm having a similar issue. Was the main fix to update you jupyter notebook?
> How can I update my jupyter notebook if I just updated anaconda?
> 
> ImportError Traceback (most recent call last)
> in 
> 2 import matplotlib as plt
> 3 from scipy.stats import ttest_ind
> ----> 4 import statsmodels.api as sm
> 
> /anaconda3/lib/python3.6/site-packages/statsmodels/api.py in 
> 5 from . import regression
> 6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
> ----> 7 from .regression.recursive_ls import RecursiveLS
> 8 from .regression.quantile_regression import QuantReg
> 9 from .regression.mixed_linear_model import MixedLM
> 
> /anaconda3/lib/python3.6/site-packages/statsmodels/regression/recursive_ls.py in 
> 14 from statsmodels.regression.linear_model import OLS
> 15 from statsmodels.tools.data import _is_using_pandas
> ---> 16 from statsmodels.tsa.statespace.mlemodel import (
> 17 MLEModel, MLEResults, MLEResultsWrapper)
> 18 from statsmodels.tools.tools import Bunch
> 
> /anaconda3/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py in 
> 27 from statsmodels.tools.tools import pinv_extended, Bunch
> 28 from statsmodels.tools.sm_exceptions import PrecisionWarning
> ---> 29 import statsmodels.genmod._prediction as pred
> 30 from statsmodels.genmod.families.links import identity
> 31 import warnings
> 
> /anaconda3/lib/python3.6/site-packages/statsmodels/genmod/**init**.py in 
> ----> 1 from statsmodels import PytestTester
> 2 test = PytestTester()
> 3
> 
> ImportError: cannot import name 'PytestTester'

I have the similar track back error msg and still seeking for solutions. Have you solved it yet?

**Comment by dineshdaultani** [comment]
Based on @jradis @MVXHAOIUTW comments, I resolved by updating ipython.
In case if anybody is looking for command: 
**conda update ipython**

**Comment by chjq201410695** [comment]
some else update?  the error is always being  even though I have tried all solutions mentioned above.

**Comment by bashtage** [comment]
You need to update ipython to a recent version.  7.5 works fine.

**Comment by bashtage** [comment]
This cannot be reproduced, so closing.  Please reopen if this is an issue.

**Comment by summiii** [comment]
I am still having the same error even after updating ipython to 7.5.0

![image](https://user-images.githubusercontent.com/19874191/60094746-8e39f000-976a-11e9-826a-d8122ed16159.png)

**Comment by bashtage** [comment]
Are you running 0.10.0?  If not, you should upgrade.

**Comment by summiii** [comment]
Hi. After updating the ipython i restarted the kernel and it worked.
Thanks
