### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [statsmodels/statsmodels#8287]
Currently Python 3.11 isn't fully supported in statsmodels yet, including testing in CI and publishing wheels to PyPI.

Python 3.11 is [now in beta](https://blog.python.org/2022/05/python-3110b1-is-now-available.html) and feature stable. By testing Python 3.11 in CI we can catch errors and bugs before Python 3.11 will become stable, and packages dependent on statsmodels can start working on their Python 3.11 support. statsmodels is one of the most used packages and a package on which many other packages depend, so early support will help speed up Python 3.11 adoption.

Python 3.11 is expected to be released as stable in October 2022, with many new features including:

> - [PEP 657](https://www.python.org/dev/peps/pep-0657/) -- Include Fine-Grained Error Locations in Tracebacks
> - [PEP 654](https://www.python.org/dev/peps/pep-0654/) -- Exception Groups and except*
> - [PEP 673](https://www.python.org/dev/peps/pep-0673/) -- Self Type
> - [PEP 646](https://www.python.org/dev/peps/pep-0646/)-- Variadic Generics
> - [PEP 680](https://www.python.org/dev/peps/pep-0680/)-- tomllib: Support for Parsing TOML in the Standard Library
> - [PEP 675](https://www.python.org/dev/peps/pep-0675/)-- Arbitrary Literal String Type
> - [PEP 655](https://www.python.org/dev/peps/pep-0655/)-- Marking individual TypedDict items as required or potentially-missing
> - [bpo-46752](https://bugs.python.org/issue46752)-- Introduce task groups to asyncio
> - The [Faster Cpython Project](https://github.com/faster-cpython) is already yielding some exciting results. Python 3.11 is up to 10-60% faster than Python 3.10. On average, we measured a 1.22x speedup on the standard benchmark suite. See [Faster CPython for details.](https://docs.python.org/3.11/whatsnew/3.11.html#faster-cpython)

Among others, [Numpy](https://github.com/numpy/numpy/pull/21308) and [SciPy](https://github.com/scipy/scipy/pull/16206) and can now be built on their main branches with Python 3.11, and [Pandas](https://github.com/pandas-dev/pandas/issues/46680) is also working on their 3.11 support.

**Comment by bashtage** [comment]
Python 3.11 support will likely only be available once NumPy, SciPy, Cython and Pandas have wheels available for 3.11, which won't happen until their first release after 3.11.0.

**Comment by EwoutH** [comment]
We could start with testing in CI, fixing bugs that come up and 

NumPy, SciPy and Cython built and fine on

**Comment by bashtage** [comment]
We are already testing against pre-releases of NumPy, Scipy and pandas.  We don't directly use the Python C API afaik, and so as long as Cython is generating correct C code, we won't have any issues.  I don't think it worth the effort.  This said, if you want to setup a CI using pre-prelease wheels for NumPy and Python 3.11 beta, I would accept the PR.

**Comment by hrnciar** [comment]
In Fedora we are rebuilding all packages with Python 3.11. statsmodels fails with:

~~~~
statsmodels/tsa/_innovations.c: In function ‘__Pyx_PyErr_GetTopmostException’:
statsmodels/tsa/_innovations.c:20057:21: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20057 |     while ((exc_info->exc_type == NULL || exc_info->exc_type == Py_None) &&
      |                     ^~
statsmodels/tsa/_innovations.c:20057:51: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20057 |     while ((exc_info->exc_type == NULL || exc_info->exc_type == Py_None) &&
      |                                                   ^~
statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionSave’:
statsmodels/tsa/_innovations.c:20071:21: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20071 |     *type = exc_info->exc_type;
      |                     ^~
statsmodels/tsa/_innovations.c:20073:19: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20073 |     *tb = exc_info->exc_traceback;
      |                   ^~
statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionReset’:
statsmodels/tsa/_innovations.c:20087:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20087 |     tmp_type = exc_info->exc_type;
      |                        ^~
statsmodels/tsa/_innovations.c:20089:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20089 |     tmp_tb = exc_info->exc_traceback;
      |                      ^~
statsmodels/tsa/_innovations.c:20090:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20090 |     exc_info->exc_type = type;
      |             ^~
statsmodels/tsa/_innovations.c:20092:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20092 |     exc_info->exc_traceback = tb;
      |             ^~
statsmodels/tsa/_innovations.c: In function ‘__Pyx__GetException’:
statsmodels/tsa/_innovations.c:20149:28: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20149 |         tmp_type = exc_info->exc_type;
      |                            ^~
statsmodels/tsa/_innovations.c:20151:26: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20151 |         tmp_tb = exc_info->exc_traceback;
      |                          ^~
statsmodels/tsa/_innovations.c:20152:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20152 |         exc_info->exc_type = local_type;
      |                 ^~
statsmodels/tsa/_innovations.c:20154:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20154 |         exc_info->exc_traceback = local_tb;
      |                 ^~
statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionSwap’:
statsmodels/tsa/_innovations.c:20187:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20187 |     tmp_type = exc_info->exc_type;
      |                        ^~
statsmodels/tsa/_innovations.c:20189:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20189 |     tmp_tb = exc_info->exc_traceback;
      |                      ^~
statsmodels/tsa/_innovations.c:20190:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
20190 |     exc_info->exc_type = *type;
      |             ^~
statsmodels/tsa/_innovations.c:20192:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
20192 |     exc_info->exc_traceback = *tb;
      |             ^~
statsmodels/tsa/_innovations.c: In function ‘__Pyx_AddTraceback’:
statsmodels/tsa/_innovations.c:465:62: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’}
  465 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
      |                                                              ^~
statsmodels/tsa/_innovations.c:20798:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
20798 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~


See https://docs.python.org/3.11/whatsnew/3.11.html#other-cpython-implementation-changes

> The interpreter state’s representation of handled exceptions (a.k.a exc_info, or _PyErr_StackItem) now has only the exc_value field, exc_type and exc_traceback have been removed as their values can be derived from exc_value.

For a full log see: https://kojipkgs.fedoraproject.org//work/tasks/8082/88568082/build.log

**Comment by bashtage** [comment]
Needs upstream fix in Cython.

**Comment by hrnciar** [comment]
I've managed to build it. Cython is fixed, but sources need to be regenerated.

**Comment by EwoutH** [comment]
We're a far months further, so here a quick update on the ecosystem!

Python 3.11 is now ABI stable with the release candidate series, which means wheels can be uploaded to PyPI!

> Python 3.11 support will likely only be available once NumPy, SciPy, Cython and Pandas have wheels available for 3.11

We're quite far now:
 - NumPy added Python 3.11 wheels with the [1.23.2 release](https://github.com/numpy/numpy/releases/tag/v1.23.2)
 - Cython added Python 3.11 wheels with the [0.29.30 release](https://github.com/cython/cython/releases/tag/0.29.30)
 - Pandas added Python 3.11 wheels with the [1.5.0 release](https://github.com/pandas-dev/pandas/releases/tag/v1.5.0)
 - SciPy working hard to get Python 3.11 wheels in the 1.9.2 and 1.10.0 releases (see https://github.com/scipy/scipy/issues/16851)

> Needs upstream fix in Cython.

This is in since Cython 0.29.29!

**Comment by jarrodmillman** [comment]
SciPy Python 3.11 wheels are now available: https://pypi.org/project/scipy/1.9.2/

**Comment by EwoutH** [comment]
It looks like currently an error building 'statsmodels.tsa._innovations' extension [appears](https://github.com/quaquel/EMAworkbench/actions/runs/3213672441/jobs/5253509452#step:4:1886):
<details><summary>Error log building Statsmodels with Python 3.11 on Ubuntu: </summary>

```
    UPDATING build/lib.linux-x86_64-cpython-311/statsmodels/_version.py
      set build/lib.linux-x86_64-cpython-311/statsmodels/_version.py to '0.13.2'
      running build_ext
      building 'statsmodels.tsa._stl' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      INFO: C compiler: gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/statsmodels
      creating build/temp.linux-x86_64-cpython-311/statsmodels/tsa
      INFO: compile options: '-DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11 -c'
      INFO: gcc: statsmodels/tsa/_stl.c
      INFO: gcc -pthread -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib build/temp.linux-x86_64-cpython-311/statsmodels/tsa/_stl.o -L/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/lib -L/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -lnpymath -lm -o build/lib.linux-x86_64-cpython-311/statsmodels/tsa/_stl.cpython-311-x86_64-linux-gnu.so
      building 'statsmodels.tsa.holtwinters._exponential_smoothers' extension
      INFO: C compiler: gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
      creating build/temp.linux-x86_64-cpython-311/statsmodels/tsa/holtwinters
      INFO: compile options: '-DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11 -c'
      INFO: gcc: statsmodels/tsa/holtwinters/_exponential_smoothers.c
      INFO: gcc -pthread -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib build/temp.linux-x86_64-cpython-311/statsmodels/tsa/holtwinters/_exponential_smoothers.o -L/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/lib -L/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -lnpymath -lm -o build/lib.linux-x86_64-cpython-311/statsmodels/tsa/holtwinters/_exponential_smoothers.cpython-311-x86_64-linux-gnu.so
      building 'statsmodels.tsa.exponential_smoothing._ets_smooth' extension
      INFO: C compiler: gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
      creating build/temp.linux-x86_64-cpython-311/statsmodels/tsa/exponential_smoothing
      INFO: compile options: '-DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11 -c'
      INFO: gcc: statsmodels/tsa/exponential_smoothing/_ets_smooth.c
      INFO: gcc -pthread -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib build/temp.linux-x86_64-cpython-311/statsmodels/tsa/exponential_smoothing/_ets_smooth.o -L/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/lib -L/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib -lnpymath -lm -o build/lib.linux-x86_64-cpython-311/statsmodels/tsa/exponential_smoothing/_ets_smooth.cpython-311-x86_64-linux-gnu.so
      building 'statsmodels.tsa._innovations' extension
      INFO: C compiler: gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
      INFO: compile options: '-DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11 -c'
      INFO: gcc: statsmodels/tsa/_innovations.c
      statsmodels/tsa/_innovations.c:16924:3: warning: excess elements in struct initializer
      16924 |   0, /*tp_inline_values_offset*/
            |   ^
      statsmodels/tsa/_innovations.c:16924:3: note: (near initialization for ‘__pyx_type___pyx_array’)
      statsmodels/tsa/_innovations.c:17046:3: warning: excess elements in struct initializer
      17046 |   0, /*tp_inline_values_offset*/
            |   ^
      statsmodels/tsa/_innovations.c:17046:3: note: (near initialization for ‘__pyx_type___pyx_MemviewEnum’)
      statsmodels/tsa/_innovations.c:17310:3: warning: excess elements in struct initializer
      17310 |   0, /*tp_inline_values_offset*/
            |   ^
      statsmodels/tsa/_innovations.c:17310:3: note: (near initialization for ‘__pyx_type___pyx_memoryview’)
      statsmodels/tsa/_innovations.c:17459:3: warning: excess elements in struct initializer
      17459 |   0, /*tp_inline_values_offset*/
            |   ^
      statsmodels/tsa/_innovations.c:17459:3: note: (near initialization for ‘__pyx_type___pyx_memoryviewslice’)
      statsmodels/tsa/_innovations.c: In function ‘__Pyx_PyBytes_Equals’:
      statsmodels/tsa/_innovations.c:19791:13: warning: ‘ob_shash’ is deprecated [-Wdeprecated-declarations]
      19791 |             hash1 = ((PyBytesObject*)s1)->ob_shash;
            |             ^~~~~
      In file included from /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/bytesobject.h:62,
                       from /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/Python.h:50,
                       from statsmodels/tsa/_innovations.c:39:
      /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/cpython/bytesobject.h:7:35: note: declared here
          7 |     Py_DEPRECATED(3.11) Py_hash_t ob_shash;
            |                                   ^~~~~~~~
      statsmodels/tsa/_innovations.c:19792:13: warning: ‘ob_shash’ is deprecated [-Wdeprecated-declarations]
      19792 |             hash2 = ((PyBytesObject*)s2)->ob_shash;
            |             ^~~~~
      In file included from /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/bytesobject.h:62,
                       from /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/Python.h:50,
                       from statsmodels/tsa/_innovations.c:39:
      /opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11/cpython/bytesobject.h:7:35: note: declared here
          7 |     Py_DEPRECATED(3.11) Py_hash_t ob_shash;
            |                                   ^~~~~~~~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx_PyErr_GetTopmostException’:
      statsmodels/tsa/_innovations.c:20057:21: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20057 |     while ((exc_info->exc_type == NULL || exc_info->exc_type == Py_None) &&
            |                     ^~
      statsmodels/tsa/_innovations.c:20057:51: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20057 |     while ((exc_info->exc_type == NULL || exc_info->exc_type == Py_None) &&
            |                                                   ^~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionSave’:
      statsmodels/tsa/_innovations.c:20071:21: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20071 |     *type = exc_info->exc_type;
            |                     ^~
      statsmodels/tsa/_innovations.c:20073:19: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20073 |     *tb = exc_info->exc_traceback;
            |                   ^~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionReset’:
      statsmodels/tsa/_innovations.c:20087:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20087 |     tmp_type = exc_info->exc_type;
            |                        ^~
      statsmodels/tsa/_innovations.c:20089:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20089 |     tmp_tb = exc_info->exc_traceback;
            |                      ^~
      statsmodels/tsa/_innovations.c:20090:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20090 |     exc_info->exc_type = type;
            |             ^~
      statsmodels/tsa/_innovations.c:20092:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20092 |     exc_info->exc_traceback = tb;
            |             ^~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx__GetException’:
      statsmodels/tsa/_innovations.c:20149:28: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20149 |         tmp_type = exc_info->exc_type;
            |                            ^~
      statsmodels/tsa/_innovations.c:20151:26: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20151 |         tmp_tb = exc_info->exc_traceback;
            |                          ^~
      statsmodels/tsa/_innovations.c:20152:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20152 |         exc_info->exc_type = local_type;
            |                 ^~
      statsmodels/tsa/_innovations.c:20154:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20154 |         exc_info->exc_traceback = local_tb;
            |                 ^~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx__ExceptionSwap’:
      statsmodels/tsa/_innovations.c:20187:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20187 |     tmp_type = exc_info->exc_type;
            |                        ^~
      statsmodels/tsa/_innovations.c:20189:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20189 |     tmp_tb = exc_info->exc_traceback;
            |                      ^~
      statsmodels/tsa/_innovations.c:20190:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
      20190 |     exc_info->exc_type = *type;
            |             ^~
      statsmodels/tsa/_innovations.c:20192:13: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
      20192 |     exc_info->exc_traceback = *tb;
            |             ^~
      statsmodels/tsa/_innovations.c: In function ‘__Pyx_AddTraceback’:
      statsmodels/tsa/_innovations.c:465:62: error: dereferencing pointer to incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        465 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
            |                                                              ^~
      statsmodels/tsa/_innovations.c:20798:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
      20798 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      error: Command "gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-a7od52yy/overlay/lib/python3.11/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/include/python3.11 -c statsmodels/tsa/_innovations.c -o build/temp.linux-x86_64-cpython-311/statsmodels/tsa/_innovations.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for statsmodels
```</details>

@bashtage Would you know how to resolve this issue?

**Comment by EwoutH** [comment]
I also opened an [draft PR](https://github.com/statsmodels/statsmodels/pull/8428) which tests Python 3.11 on the Azure pipelines CI, so that all errors can be detected there. See the first run [here](https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4662&view=results).

**Comment by bashtage** [comment]
I would report the compilation issue to Cython, since this works fine on Python 3.8-3.10.

**Comment by bashtage** [comment]
All of the referenced code is the type either provided by Python or Cython.

**Comment by EwoutH** [comment]
Thanks for getting back! I found an abandoned PR over at the Cython repo that looked a lot like the error we're experiencing, so I asked if it could be the same issue.

**Comment by da-woods** [comment]
@EwoutH all the code that's giving you errors should be disabled by https://github.com/cython/cython/blob/f2e8b2f3dca7436630b1b4a4d42305adcf173ece/Cython/Utility/ModuleSetupCode.c#L257-L260 so I'm a bit puzzled what's going on.

**Comment by da-woods** [comment]
If I try to install pip install statmodels with Python 3.11 I get the same error. However the failing file (`_innovations.c`, and also `_qn.c`) starts with

```
/* Generated by Cython 0.29.25 */
```

which I believe predates the fix. All the other C files look to be generated by Cython 0.29.32. So I don't think this is a Cython bug

**Comment by bashtage** [comment]
You should build from main first.  The gzip contains cythonized pyx to c files since cython isn't required to build statsmodel.

**Comment by EwoutH** [comment]
I found some more things.

**Buidling**
- With both Cython 0.29.32 and 3.0.0a11 the statsmodels main branch compiles fine on Python 3.11 🎉
- The latest release is of statsmodels is [0.13.2](https://github.com/statsmodels/statsmodels/releases/tag/v0.13.2), which only [requires](https://github.com/statsmodels/statsmodels/blob/v0.13.2/pyproject.toml#L5) cython>=0.29.22. So if the Cython version is a bit older and isn't updated when building, it will fail.

**Tests**
- The tests currently fail, and that is due to [this issue](https://github.com/pydata/patsy/issues/186) in patsy, an upstream dependency for the statsmodels tests. They fixed this issue on their main branch in [this PR](https://github.com/pydata/patsy/pull/187), but there isn't any release available. So we have to either wait for a new release (I [asked](https://github.com/pydata/patsy/pull/187#issuecomment-1272595333)), use a specific commit on their main branch or fix is on our side.

Considering this, I think requiring cython>=0.29.32 on the [maintenance/0.13.x](https://github.com/statsmodels/statsmodels/tree/maintenance/0.13.x) branch, test if it builds for Python 3.11 (including wheels) and then tagging a new release on the would be a good course of action.

**Comment by EwoutH** [comment]
The maintainer of patsy responded very quick and already tagged a [new release](https://github.com/pydata/patsy/releases/tag/v0.5.3), with the fix in it!

I [retriggered the CI](https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4665&view=results), and the Linux and macOS jobs pass! On Windows it still [fails](https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4664&view=logs&j=c203999b-4fb3-5854-a733-83d14a010489&t=84c4483e-70f5-5851-7133-396b4a3130f5&l=603) unfortunately, an issue with one of the dependencies, libxml. It might be [this one](https://bugs.launchpad.net/lxml/+bug/1969912) but I'm not sure.

**Comment by benz0li** [comment]
With Python 3.11 now available, it would be great to have wheels for it soon.

**Comment by bashtage** [comment]
I suspect that 3.11 wheels won't' be available until 0.14 is released.

**Comment by benz0li** [comment]
The current release ([0.13.2](https://github.com/statsmodels/statsmodels/releases/tag/v0.13.2)) does not build with Python 3.11.

This issue is not assigned to any milestone. Will there be another minor release when this issue is fixed?

**Comment by bashtage** [comment]
I doubt it.  I suspect that 0.13.x won't have any more point releases.  This is the usual procedure.

**Comment by EwoutH** [comment]
CI Is green and passing, so https://github.com/statsmodels/statsmodels/pull/8431 can be merged. 

The next step is indeed building and publishing wheels. Can we do an extra patch release on the 0.13.x branch just for Python 3.11 support? That should be very useful, since many project depend on statsmodels and want to get going with Python 3.11 building and testing.

**Comment by EwoutH** [comment]
So now we need to ship Python 3.11 support to users. We could either start backports to the 0.13.x branch, or prepare for 0.14.0 release.

@bashtage what would be your preferred course of action?

**Comment by EwoutH** [comment]
If you want to go the backport route, I started a draft PR with backports here:

- #8467

**Comment by EwoutH** [comment]
@bashtage What do you have in mind for the statsmodels 0.14 release? Is there some timeline or are there some features you want to get in? Can we release it relatively soon? What steps are needed for that?

Backporting a year of changes to 0.13.x is going to be a major effort, so maybe releasing 0.14 is just easier. 0.13.0 is now over a year old so a new release to get all improvements and features out might be a good idea anyway!

**Comment by josef-pkt** [comment]
I need maybe 2 weeks of work for 0.14.
There are at most a few smaller PRs that can still go in.
I still need more API work on my new features that are in 0.14/main.
The problem is that I have been quite distracted and have not spend enough time on statsmodels 0.14.

How about 0.14rc1 in around two weeks?
(That would put enough pressure on me to finish the API decisions and cleanup.)

**Comment by EwoutH** [comment]
> How about 0.14rc1 in around two weeks?

If that’s a workable timeframe, sounds good! Keep us in the loop.

**Comment by bashtage** [comment]
Wheels for 3.11 are out now for statsmodels 0.13.3.

https://pypi.org/project/statsmodels/#files

**Comment by benz0li** [comment]
Thank you @bashtage

**Comment by EwoutH** [comment]
Awesome, thank you a lot!

**Comment by EwoutH** [comment]
> How about 0.14rc1 in around two weeks?
> (That would put enough pressure on me to finish the API decisions and cleanup.)

I was curious how it's going! Any difficult decisions left yet?

**Comment by josef-pkt** [comment]
I lost the pressure after the 0.13 releases.
(and then I get sometimes more interested in a novel than doing statsmodels maintenance, I'm not getting any money for it anyway)

I need at most a few more days, only one PR that I really would like to get in (tweedie), plus minor issues that I can still find.

**Comment by EwoutH** [comment]
Python 3.12 is now in beta, so I opened a new tracking issue for it: https://github.com/statsmodels/statsmodels/issues/8914
