### ISSUE TITLE
FAQ: Statsmodels 0.9/Scipy 1.3.0 incompatibility

### ISSUE THREAD

**Issue by thve** [statsmodels/statsmodels#5759]
#### Describe the bug

Hello,

Since release [1.3.0](https://github.com/scipy/scipy/releases/tag/v1.3.0) of Scipy aliases from scipy.misc (comb, factorial, factorial2, factorialk, logsumexp, pade, info, source, who) which have been deprecated since v1.0.0 are removed.

Resulting in incompatibility between statsmodels and scipy.

#### Code Sample, a copy-pastable example if possible

In a python 3 env

```shell
pip install statsmodels
pip install scipy
```

Then in a python shell

```python
import statsmodels.stats.api as sm
# ImportError: cannot import name 'comb' from 'scipy.misc'
```

#### Expected Output
statsmodels is working with scipy 1.2.1 but it will be better than statsmodels stay compatible with last scipy release.

**Comment by mfschmidt** [comment]
According to [bashtage](https://github.com/statsmodels/statsmodels/issues/5747#issuecomment-493667058) at [#5747](https://github.com/statsmodels/statsmodels/issues/5747) you can install from the master branch and everything works. I tried this as follows:

    pip install --upgrade Cython
    pip install --upgrade git+https://github.com/statsmodels/statsmodels

It seemed to resolve the issue for me, so far.

**Comment by bashtage** [comment]
statsmodels 0.9 is not compatible with SciPy 1.3.0.  The current master branch is compatible and the next release will be compatible.  The options are to downgrade SciPy, install in a virtual- or conda-env with SciPy 1.2, or to install from master using the code provided above.

**Comment by stonebig** [comment]
when is the next release ?

**Comment by ptornich** [comment]
Is there any predictions for a pypi release?

**Comment by bashtage** [comment]
June

**Comment by tiffanyhsu001** [comment]
after installing from master:
pip install --upgrade git+https://github.com/statsmodels/statsmodels

i get this new (similar) error: 
ImportError: cannot import name 'factorial' from 'statsmodels.compat.scipy' 

someone help?

**Comment by bashtage** [comment]
You need to make sure you have removed any previous version

Run this command a few times until you get a message that it isn't installed. 

```
pip uninstall statsmodels -y
```

This is not a bug in master so something is wrong with the one installed.

**Comment by tiffanyhsu001** [comment]
@bashtage fixed it thank you!

**Comment by mhooreman** [comment]
Hello,

If it can help anybody, here's a shell script workaround in the meanwhile.

```bash
#!/usr/bin/env bash

# Attention: this patches scipy => when statmodels is fixed, you need to
#            re-install scipy in order to "unpatch" it

initPy=$(pip show scipy | grep 'Location' | awk -F ': ' '{print $2"/scipy/misc/__init__.py"}')

cat <<EOF >>$initPy

# https://github.com/statsmodels/statsmodels/issues/5759 workaround
from ..special import factorial, logsumexp, comb
__all__ += ['factorial', 'logsumexp', 'comb']
EOF 
```

Best regards.

**Comment by KonstantinDoronin** [comment]
hi, update till the current moment.
1.Delete modules Scipi and statmodels (any version)
2. Install scipi last vestion
3. Install statmodels module
and it works!

**Comment by Juanlu001** [comment]
If you want to keep stable statsmodels:

```
pip install "scipy<1.3"
```

(don't do this if you installed SciPy with conda)

If you want to try the upcoming statsmodels version while keeping the latest scipy:

```
pip install --pre statsmodels
```

**Comment by clemenspeters** [comment]
Thanks @bashtage

 1. `pip install statsmodels==0.10.0rc2 --pre`

 2. **Restarting the kernel** of the jupyter notebook

fixed it for me.<br>
You can check your versions with `pip list`

**Comment by bashtage** [comment]
0.10.0 has been released.  Only sdist is on PyPI.  Wheels should follow in the next day or so.

**Comment by bhattaraiprabhat** [comment]
@mfschmidt: Yes it fixes the issue.

**Comment by bhattaraiprabhat** [comment]
Thanks  @bashtage,@ clemenspeters:
Finally,  1. pip install statsmodels==0.10.0rc2 --pre

              2. Restarting the kernel of the jupyter notebook (Must)
Solved the issue!
