### ISSUE TITLE
AttributeError: 'AutoRegResults' object has no attribute 'apply'

### ISSUE THREAD

**Issue by laniakea** [statsmodels/statsmodels#8814]
I'm not sure what makes this wrong:

```
model = AutoReg(X, lags = L)
model_fit = model.fit()
result = model_fit.predict(start=N-M+1, end=N-M+steps) # the indecis are inclusive unlike np arrays
new_res = model_fit.apply(result)
```

But I get
AttributeError: 'AutoRegResults' object has no attribute 'apply'

Message. According to the following:
https://www.statsmodels.org/dev/generated/statsmodels.tsa.ar_model.AutoRegResults.apply.html
there shouldn't be a problem.

**Comment by bashtage** [comment]
Are you using the released version or the main branch from GitHub.  That feature is only in the dev branch.

**Comment by bashtage** [comment]
Your example works on main but not 0.13.  The new release should be out in the next few weeks.

**Comment by laniakea** [comment]
Thanks. The version I'm using is 0.13.5
