### ISSUE TITLE
AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by PVinay737** [statsmodels/statsmodels#6600]
#### Describe the bug

Trying  `>>> import statsmodels.sandbox.stats.multicomp`

#### Getting Following Errors
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/sandbox/__init__.py", line 4, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/numpy.py", line 46, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'

```

**Comment by bashtage** [comment]
You seem to have an ancient numpy; You are also using python 2 which is not supported.  

Don't use your system python. Use Anaconda.

**Comment by PVinay737** [comment]
It works for Python3.7 but I want to work with Python2.7 and also my numpy version is `1.16.6`

**Comment by bashtage** [comment]
As it says above, Python 2 is not supported.

**Comment by PVinay737** [comment]
Will try to migrate to Python 3. 

Thank You !
