### ISSUE TITLE
cannot import name 'iteritems' from 'statsmodels.compat.python'

### ISSUE THREAD

**Issue by chsher** [statsmodels/statsmodels#7809]
I am trying to install statsmodels but am running into an error when I try to load the package: cannot import name 'iteritems' from 'statsmodels.compat.python'. I am working with python 3.8.5 and statsmodels 0.11.1.

**Comment by chsher** [comment]
Thank you -- all set!
